import { Strings } from '@/types';

export const en: Strings = {
  title: 'Spoke Route Bridge',
  subtitle: 'Match WhatsApp names to your master list and export a Spoke-compatible CSV.',
  uploadTitle: 'Master Customer List',
  uploadSubtitle: 'Upload your Excel or CSV master file',
  uploadHint: 'Drag & drop or click to select an .xlsx, .xls, or .csv file',
  selectSheet: 'Select sheet',
  mapColumns: 'Map columns',
  nameColumn: 'Customer Name column',
  addressColumn: 'Address column',
  saveList: 'Save to cache',
  listCached: 'List cached',
  clearList: 'Clear cache',
  inputTitle: 'WhatsApp Names',
  inputPlaceholder:
    'Paste names from WhatsApp here (one per line, commas, or mixed with phone numbers / timestamps)...',
  matchBtn: 'Match Names',
  resultsTitle: 'Match Results',
  inputName: 'Input Name',
  matchedTo: 'Matched To',
  address: 'Address',
  confidence: 'Score',
  override: 'Override',
  searchPlaceholder: 'Search customer...',
  downloadCsv: 'Download Spoke CSV',
  copyAddresses: 'Copy Addresses',
  copied: 'Copied!',
  noMatch: 'No match found',
  pendingReview: 'needs review',
  rowCount: 'rows',
};

export const ro: Strings = {
  title: 'Spoke Route Bridge',
  subtitle: 'Potrivește numele din WhatsApp cu lista master și exportă un CSV pentru Spoke.',
  uploadTitle: 'Lista Master Clienți',
  uploadSubtitle: 'Încarcă fișierul Excel sau CSV principal',
  uploadHint: 'Trage & aruncă sau dă clic pentru a selecta un fișier .xlsx, .xls sau .csv',
  selectSheet: 'Selectează foaie',
  mapColumns: 'Configurează coloane',
  nameColumn: 'Coloana Nume Client',
  addressColumn: 'Coloana Adresă',
  saveList: 'Salvează în cache',
  listCached: 'Listă salvată',
  clearList: 'Șterge cache',
  inputTitle: 'Nume din WhatsApp',
  inputPlaceholder:
    'Lipește numele din WhatsApp (unul pe linie, separate prin virgulă, sau amestecate cu numere de telefon / marcaje de timp)...',
  matchBtn: 'Potrivește Numele',
  resultsTitle: 'Rezultate Potrivire',
  inputName: 'Nume Introdus',
  matchedTo: 'Potrivit Cu',
  address: 'Adresă',
  confidence: 'Scor',
  override: 'Modifică',
  searchPlaceholder: 'Caută client...',
  downloadCsv: 'Descarcă CSV Spoke',
  copyAddresses: 'Copiază Adresele',
  copied: 'Copiat!',
  noMatch: 'Nicio potrivire',
  pendingReview: 'necesită revizuire',
  rowCount: 'rânduri',
};
